project:
  type: website
  output-dir: _site

website:
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    title: "GeoZarr"
    tools:
      - icon: github
        href: https://github.com/developmentseed/geozarr-examples
        text: "Repo"
    contents:
      - href: index.qmd
        text: Home
      - href: spec-diagram.qmd
        text: Visual explainer
      - href: web-optimized-zarr.qmd
        text: Web-optimized Zarr (WOZ)
      - href: woz-diagram.qmd
        text: Visual WOZ comparison
      - section: Presentations
        contents:
        - href: slides/2025-02.qmd
          text: Team week (February 2025)
        - href: slides/2025-04.qmd
          text: STAC & Zarr workshop (April 2025)
      - section: Pre-requisites
        contents:
          - href: examples/00_download_data.ipynb
            text: Download dataset for examples
      - section: Examples
        contents:
          - href: examples/01_CRS_in_auxiliary_variable.ipynb
            text: Explicit coordinates
          - href: examples/02_CRS_and_geotransform_in_auxiliary_variable.ipynb
            text: GeoTransform
          - href: examples/03_multiscales_as_WebMercatorQuad_ZarrV2.ipynb
            text: WebMercatorQuad overviews (Zarr V2)
          - href: examples/04_multiscales_as_WebMercatorQuad_ZarrV3.ipynb
            text: WebMercatorQuad overviews (Zarr V3)
          - href: examples/06_embedded_STAC_block.ipynb
            text: STAC metadata

format:

  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
filters:
  - quarto



