project:
  type: website
  output-dir: _site

website:
  title: "GeoZarr (in practice)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
filters:
  - quarto



